import type { TimelineCaseExample } from "./models.js";

export const timelineCaseExamples: TimelineCaseExample[] = [
  {
    id: "hook",
    title: "Hook: fast attention opener",
    semanticProject: {
      semanticId: "semantic-hook-001",
      useCase: "hook",
      title: "Hook intro",
      targetDurationMs: 8000,
      scenes: [
        {
          id: "hook-1",
          title: "Pain statement",
          summary: "Show the core pain in 1 sentence",
          text: "Tired of spending hours editing one reel?",
          targetDurationMs: 5000,
          tags: ["hook", "pain-point"],
        },
        {
          id: "hook-2",
          title: "Promise",
          summary: "Promise immediate value",
          text: "We can cut this to 10 minutes with AI-assisted timeline.",
          targetDurationMs: 3000,
          tags: ["hook", "promise"],
        },
      ],
    },
    expectedTimeline: {
      draftId: "expected-hook-draft",
      sourceSemanticId: "semantic-hook-001",
      useCase: "hook",
      totalDurationMs: 8000,
      scenes: [
        {
          id: "hook-1",
          index: 0,
          title: "Pain statement",
          startMs: 0,
          durationMs: 5000,
          mode: "ai-generated",
          prompt:
            "Generate visual scene: Pain statement. Narrative: Tired of spending hours editing one reel?",
          assetStrategy: "generate",
          tags: ["hook", "pain-point"],
        },
        {
          id: "hook-2",
          index: 1,
          title: "Promise",
          startMs: 5000,
          durationMs: 3000,
          mode: "ai-generated",
          prompt:
            "Generate visual scene: Promise. Narrative: We can cut this to 10 minutes with AI-assisted timeline.",
          assetStrategy: "generate",
          tags: ["hook", "promise"],
        },
      ],
      tracks: [
        {
          id: "track-video",
          kind: "video",
          sceneIds: ["hook-1", "hook-2"],
        },
        {
          id: "track-audio",
          kind: "audio",
          sceneIds: ["hook-1", "hook-2"],
        },
      ],
      warnings: [],
    },
  },
  {
    id: "one-minute-script",
    title: "1 minute explainer script",
    semanticProject: {
      semanticId: "semantic-script-001",
      useCase: "one-minute-script",
      title: "One minute flow",
      targetDurationMs: 60000,
      globalInstructions: "Tone: energetic, practical, no buzzwords.",
      scenes: [
        {
          id: "s1",
          title: "Hook",
          summary: "Open with measurable pain",
          text: "Most teams lose 2 days per week on repetitive edits.",
          targetDurationMs: 10000,
          mode: "teleprompter",
          tags: ["script", "hook"],
        },
        {
          id: "s2",
          title: "Context",
          summary: "Explain why this happens",
          text: "Content requests come fragmented from five channels.",
          targetDurationMs: 10000,
          mode: "teleprompter",
          tags: ["script", "context"],
        },
        {
          id: "s3",
          title: "Solution",
          summary: "Introduce semantic-to-timeline",
          text: "Semantic model turns intent into reusable timeline blocks.",
          targetDurationMs: 10000,
          mode: "teleprompter",
          tags: ["script", "solution"],
        },
        {
          id: "s4",
          title: "Proof",
          summary: "Share real effect",
          text: "Production cycle dropped from 4 hours to 35 minutes.",
          targetDurationMs: 10000,
          mode: "teleprompter",
          tags: ["script", "proof"],
        },
        {
          id: "s5",
          title: "How it works",
          summary: "Describe 3 steps",
          text: "Draft -> scene detail -> final render orchestration.",
          targetDurationMs: 10000,
          mode: "teleprompter",
          tags: ["script", "process"],
        },
        {
          id: "s6",
          title: "CTA",
          summary: "Invite pilot",
          text: "Send your next script and we return timeline in minutes.",
          targetDurationMs: 10000,
          mode: "teleprompter",
          tags: ["script", "cta"],
        },
      ],
    },
    expectedTimeline: {
      draftId: "expected-script-draft",
      sourceSemanticId: "semantic-script-001",
      useCase: "one-minute-script",
      totalDurationMs: 60000,
      scenes: [
        {
          id: "s1",
          index: 0,
          title: "Hook",
          startMs: 0,
          durationMs: 10000,
          mode: "teleprompter",
          prompt:
            "Deliver script for scene: Hook. Text: Most teams lose 2 days per week on repetitive edits. Global: Tone: energetic, practical, no buzzwords.",
          assetStrategy: "record-upload",
          tags: ["script", "hook"],
        },
        {
          id: "s2",
          index: 1,
          title: "Context",
          startMs: 10000,
          durationMs: 10000,
          mode: "teleprompter",
          prompt:
            "Deliver script for scene: Context. Text: Content requests come fragmented from five channels. Global: Tone: energetic, practical, no buzzwords.",
          assetStrategy: "record-upload",
          tags: ["script", "context"],
        },
        {
          id: "s3",
          index: 2,
          title: "Solution",
          startMs: 20000,
          durationMs: 10000,
          mode: "teleprompter",
          prompt:
            "Deliver script for scene: Solution. Text: Semantic model turns intent into reusable timeline blocks. Global: Tone: energetic, practical, no buzzwords.",
          assetStrategy: "record-upload",
          tags: ["script", "solution"],
        },
        {
          id: "s4",
          index: 3,
          title: "Proof",
          startMs: 30000,
          durationMs: 10000,
          mode: "teleprompter",
          prompt:
            "Deliver script for scene: Proof. Text: Production cycle dropped from 4 hours to 35 minutes. Global: Tone: energetic, practical, no buzzwords.",
          assetStrategy: "record-upload",
          tags: ["script", "proof"],
        },
        {
          id: "s5",
          index: 4,
          title: "How it works",
          startMs: 40000,
          durationMs: 10000,
          mode: "teleprompter",
          prompt:
            "Deliver script for scene: How it works. Text: Draft -> scene detail -> final render orchestration. Global: Tone: energetic, practical, no buzzwords.",
          assetStrategy: "record-upload",
          tags: ["script", "process"],
        },
        {
          id: "s6",
          index: 5,
          title: "CTA",
          startMs: 50000,
          durationMs: 10000,
          mode: "teleprompter",
          prompt:
            "Deliver script for scene: CTA. Text: Send your next script and we return timeline in minutes. Global: Tone: energetic, practical, no buzzwords.",
          assetStrategy: "record-upload",
          tags: ["script", "cta"],
        },
      ],
      tracks: [
        {
          id: "track-video",
          kind: "video",
          sceneIds: ["s1", "s2", "s3", "s4", "s5", "s6"],
        },
        {
          id: "track-audio",
          kind: "audio",
          sceneIds: ["s1", "s2", "s3", "s4", "s5", "s6"],
        },
        {
          id: "track-subtitle",
          kind: "subtitle",
          sceneIds: ["s1", "s2", "s3", "s4", "s5", "s6"],
        },
      ],
      warnings: [],
    },
  },
  {
    id: "social-post",
    title: "Social post with meme slot",
    semanticProject: {
      semanticId: "semantic-social-001",
      useCase: "social-post",
      title: "Social promo",
      targetDurationMs: 24000,
      scenes: [
        {
          id: "sp1",
          title: "Intro",
          summary: "State offer",
          text: "Template launch: build reels from semantic script.",
          targetDurationMs: 4000,
          tags: ["social", "offer"],
        },
        {
          id: "sp2",
          title: "Meme insert",
          summary: "Add relatable meme reaction",
          text: "Insert meme asset from library about deadline panic.",
          targetDurationMs: 12000,
          mode: "user-upload",
          tags: ["social", "meme"],
        },
        {
          id: "sp3",
          title: "CTA",
          summary: "Ask to comment",
          text: "Comment 'draft' and get timeline sample.",
          targetDurationMs: 8000,
          tags: ["social", "cta"],
        },
      ],
    },
    expectedTimeline: {
      draftId: "expected-social-draft",
      sourceSemanticId: "semantic-social-001",
      useCase: "social-post",
      totalDurationMs: 24000,
      scenes: [
        {
          id: "sp1",
          index: 0,
          title: "Intro",
          startMs: 0,
          durationMs: 4000,
          mode: "ai-generated",
          prompt:
            "Generate visual scene: Intro. Narrative: Template launch: build reels from semantic script.",
          assetStrategy: "generate",
          tags: ["social", "offer"],
        },
        {
          id: "sp2",
          index: 1,
          title: "Meme insert",
          startMs: 4000,
          durationMs: 12000,
          mode: "user-upload",
          prompt:
            "Generate visual scene: Meme insert. Narrative: Insert meme asset from library about deadline panic.",
          assetStrategy: "reuse-library",
          tags: ["social", "meme"],
        },
        {
          id: "sp3",
          index: 2,
          title: "CTA",
          startMs: 16000,
          durationMs: 8000,
          mode: "ai-generated",
          prompt:
            "Generate visual scene: CTA. Narrative: Comment 'draft' and get timeline sample.",
          assetStrategy: "generate",
          tags: ["social", "cta"],
        },
      ],
      tracks: [
        {
          id: "track-video",
          kind: "video",
          sceneIds: ["sp1", "sp2", "sp3"],
        },
        {
          id: "track-audio",
          kind: "audio",
          sceneIds: ["sp1", "sp2", "sp3"],
        },
      ],
      warnings: [],
    },
  },
];
